# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('job_position', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('date_published', models.DateTimeField()),
                ('times_viewed', models.IntegerField()),
                ('publisher', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('requirements', models.CharField(max_length=300)),
                ('submitting_resume', models.CharField(max_length=300)),
                ('company_description', models.CharField(max_length=2000)),
            ],
        ),
    ]
