# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20170831_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinfo',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
